version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm install && npm start"
    volumes:
      - '.:/usr/src/app'
      - 'node_modules:/usr/src/app/node_modules'
    ports:
      - '1313:1313'
    restart: 'always'
volumes:
  node_modules:
